spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 255449b7fbcdba8ce06fe0dd5da85d13
            client-secret: T7MBOLCGFQcTe3AA5oZZA5eK0qoNmB3F
            redirect-uri: '{baseUrl}/oauth2/callback/{registrationId}'
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: profile_nickname
      provider:
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
  profiles:
    active: ${profile}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

springdoc:
  packages-to-scan: com.ssafy.server.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api/
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

# JWT Secret Key
jwt:
  secret-key: 'ThisStatementIsJwtSecretKeyDoNotUseThisStatement'
